"""add document path col

Revision ID: 1755d49c2228
Revises: 5fd5349b4751
Create Date: 2019-11-07 01:23:59.660896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1755d49c2228'
down_revision = '5fd5349b4751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('path', sa.String(length=254), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'path')
    # ### end Alembic commands ###
