"""create product table

Revision ID: 248c22a0278d
Revises: e1054c6dcae8
Create Date: 2019-11-06 22:52:33.009533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248c22a0278d'
down_revision = 'e1054c6dcae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
