"""add document title col

Revision ID: 443a6e1d2d25
Revises: 454fb708c44b
Create Date: 2019-11-08 23:11:15.574155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443a6e1d2d25'
down_revision = '454fb708c44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'title')
    # ### end Alembic commands ###
