"""add document prefix col

Revision ID: 454fb708c44b
Revises: ccda59a93e03
Create Date: 2019-11-07 02:40:59.704940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454fb708c44b'
down_revision = 'ccda59a93e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('prefix', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'prefix')
    # ### end Alembic commands ###
