"""delete document data col

Revision ID: 5fd5349b4751
Revises: aa282df8f366
Create Date: 2019-11-07 01:22:49.773806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd5349b4751'
down_revision = 'aa282df8f366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('data', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
