"""add product cols

Revision ID: 5fde58c8b56c
Revises: 443a6e1d2d25
Create Date: 2019-11-12 20:40:46.154763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fde58c8b56c'
down_revision = '443a6e1d2d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('product', sa.Column('eta', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('eta_type', sa.String(length=100), nullable=False))
    op.add_column('product', sa.Column('type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'type')
    op.drop_column('product', 'eta_type')
    op.drop_column('product', 'eta')
    op.drop_column('product', 'currency')
    # ### end Alembic commands ###
