"""add order active col

Revision ID: aa282df8f366
Revises: 55d5220a4acb
Create Date: 2019-11-07 00:46:29.455182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = 'aa282df8f366'
down_revision = '55d5220a4acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('active', sa.Boolean(), nullable=True))
    order = sa.table('order', sa.Column('active'))
    op.execute(order.update().values(**{'active': True}))
    op.alter_column('order', 'active', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'active')
    # ### end Alembic commands ###
