"""add document unique idx

Revision ID: ccda59a93e03
Revises: 1755d49c2228
Create Date: 2019-11-07 01:51:57.612821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccda59a93e03'
down_revision = '1755d49c2228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux_document_type_client_id', 'document', ['type', 'client_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_document_type_client_id', 'document', type_='unique')
    # ### end Alembic commands ###
