"""create client table

Revision ID: f1cb4b834e38
Revises: 
Create Date: 2019-10-22 22:14:42.865268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cb4b834e38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('passport_number', sa.String(length=8), nullable=False),
    sa.Column('itn', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('itn'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_client_client_code'), 'client', ['client_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_client_code'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
