print("What is your name?")
name = input("My name is: ")
print("How old are you?")
age = int(input("My age is: "))
print("Where do you live")
city = input("I live in: ")
print()
print("Hello",name)
print("Your age is",age)
print("You live in",city)
input("Press Enter to exit")